---
title: "Schedule"
format: 
  html:
    code-copy: false
---
<html>
<head>
    <style>
        body {
            -webkit-user-select: none; /* Safari */
            -moz-user-select: none; /* Firefox */
            -ms-user-select: none; /* IE10+/Edge */
            user-select: none; /* Standard */
        }
    </style>
</head>
<body>

:::{.callout-note}
**Referencing the content on this webpage:**

Bulusu, Kartik V. (2025, January). MAE 6291: Internet-of-Things for Engineers. [Course lecture notes, codes and presentations]. Department of Mechanical and Aerospace Engineering, The George Washington University.
:::

Schedule [*week-by-week*]

::: {.callout-warning appearance="simple"}
**The course schedule below will be updated on a weekly basis during the Spring 2025 semester.**
:::

<!-- ::: {.callout-important appearance="default" title="Final Project Due Date"}
The Final Project deliverables are due on **December 05, 2023, 11:59 PM**. Check-out the schedule to learn more about where to [submit all the deliverables](schedule.qmd#final-project).
::: -->

<style>
        .thumbnail {
            width: 100px; 
            cursor: pointer;
        }

        #popupContainer {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.7);
            justify-content: center;
            align-items: center;
        }

        #popupImage {
            max-width: 80%;
            max-height: 80%;
        }
    </style>

<table class="table table-hover w-auto">
  <colgroup>
    <col style="width:3%">
    <col style="width:50%">
    <col style="width:47%">
    <!-- <col style="width:32%"> -->
  </colgroup>
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Topic(s) and readings </th>
      <th scope="col">$\mu$-LABs and Assignment(s) due</th>
      <!--- <th scope="col">Column heading</th> -->
    </tr>
  </thead>
  <tbody>
    <tr class="table-secondary">
      <th scope="row">Week 0 [01/15/2025]</th>
      <td>
        <ul>
          <li>IoT and Edge Computing [The big pictures]</li> 
          <li>Introduction to Raspberry Pi and Python programming</li> 
          <li>Course overview, policies and deliverables</li>
          <li><a href="Week0.qmd" style="color:red;" target="_blank">Week-0 Notes</a></li>
        </ul>  
      </td>
      <td>
        <ul>
          <li>Getting familiar with the Raspberry Pi 4B</li>
          <li>Python programming using Thonny</li> 
          <li><strong>No HW assigned in this week</strong></li>
<!--           <li><a href="https://drive.google.com/drive/folders/1nfW_e6UMP8V1tn20zKAe9_b9Ix1DTEUw?usp=sharing" target="_blank">Lab examples</a></li> 
          <li><a href="https://drive.google.com/drive/folders/14M0NCkRZcFNnOYdubMGOuJn35kvvJhV2?usp=sharing" target="_blank">HW 1 assigned</li> --> 
        </ul>
      </td>
      <td>
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<tr class="table-secondary">
      <th scope="row">[01/20/2025]</th>
      <td colspan="2" style="text-align: center"> Martin Luther King Jr. Day 
      <br> Inauguration Day
      <br><strong>No Classes</strong>
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>

    <tr class="table-secondary">
      <th scope="row">Week 1 [01/22/2025]</th>
      <td>
        <ul>
          <li>Sneak preview at the edge-lab and hardware</li>
          <li>What is the thing in IoT?</li>
          <li>Overview of computing in IoT</li>
          <li>What is Edge Computing?</li>
          <!-- <li>Design Thinking Exercise for IoT practioners 
         **Edge Cloud** by <a href="https://www.seas.gwu.edu/timothy-wood"
          target="_blank">Prof. Tim Wood</a>, CS Department, GWU. <a href="http://faculty.cs.gwu.edu/timwood/" target="_blank">Director of GW Cloud Systems Lab</a> -->
          </li>
          <li><a href="Week1.qmd" style="color:red;" target="_blank">Week-1 Notes</a></li>
        </ul>
      </td>
      <td>
        <ul>
          <li>Setting up the Edge Lab</li>
          <li>Understanding the Python installation on the Raspberry Pi</li>
          <li>Some basic Python programming constructs</li>
          <li style="color:black"><strong>First steps in Raspberry Pi programming: Blinking LEDs [Graded Lab Activity]</strong></li>
          <li><strong>No HW assigned in this week</strong></li>
<!--           <li><a href="https://drive.google.com/drive/folders/1nfW_e6UMP8V1tn20zKAe9_b9Ix1DTEUw?usp=sharing" target="_blank">Lab examples</a></li> 
          <li><a href="https://drive.google.com/drive/folders/14M0NCkRZcFNnOYdubMGOuJn35kvvJhV2?usp=sharing" target="_blank">HW 1 assigned</li>  -->
        </ul>
      </td>
      <td>
      </td>
      <!--- <td>Column content</td> -->
    </tr>
    <tr class="table-secondary">
      <th scope="row" style="color:black">Week 2 [01/29/2025]</th>
      <td>
        <ul>
          <li>What is Edge Computing and Edge Compute device</li>
          <li>Differences in Cloud and Fog computing</li>
          <li style="color:black">Python skelton code for running programs on the Raspberry Pi</li>
          <li style="color:black">Recap of some programming constructs</li>
          <li style="color:black">Using Thonny to blink LEDs</li>
          <li style="color:black">Using bash script to blink LEDs</li>
          <li>Guest lecture: **Intersection of Industry 4.0 and Technology for Manufacturing in day-to-day applications**
         <!-- **Intersection of Industry 4.0 and Technology for Manufacturing in day-to-day applications** by <a href="/Lectures_Speakers/HadiImran-bio-Feb232024.pdf" target="_blank">Hadi Mohammed</a>, Digital Technologies Director of Factory 4.0 <a href="https://prattwhitney.com" target="_blank">Pratt and Whitney</a> -->
          </li>          
          <!-- <li style="color:black"><a href="Week2.qmd" style="color:red;" target="_blank">Week-2 Notes</a></li> -->
        </ul>
      </td>
      <td>
        <ul>
          <li style="color:black">Configuring the GPIO interface on your Raspberry Pi</li>
          <li style="color:black">In-class Raspberry Pi Lab (Blinking LEDs)</li> 
          <li style="color:black">Setting up a Python virtual environment [venv] and it's benefits</li>
          <li style="color:black">Installing Python GPIO packages with pip in [venv]</li>
          <li style="color:black"><strong>Blinking LEDs on boot [Graded Lab Activity]</strong></li>
          <!-- <li><strong><a href="Downloads/LastName_ExecutiveSummary.docx" style="color:red;" target="_blank">HW1: Guest Lecture Summary [Download Template]</a></strong></li> <strong style="color:black">HW1 Assigned: 02/04/2024; HW1 Due: 02/09/2024</strong> -->
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>

    <tr class="table-secondary">
      <th scope="row">Week 3 [02/05/2025]</th>
      <td>
        <ul>
          <li>IoT Architecture and Ecosystem</li>
          <li>Layers in IoT systems - 3 level  layer model</li>
          <li>Sensors</li>
          <li>Sensor types and considerations</li>
          <li>Understanding Analog and Digital Signals</li>
          <li>Fundamentals of signal visualization in time and frequency</li>  
          <li>Guest lecture: 
          <!-- **Designing high-confidence embedded systems -- operating systems and real-time**</a> by <a href="https://faculty.cs.gwu.edu/gparmer/"
          target="_blank">Prof. Gabe Parmer</a>, CS Department, GWU. <a href="https://composite.seas.gwu.edu" target="_blank">Parmer Lab</a> -->
          </li>     
          <!-- <li>Guest lecture: <a href="Week3-Parmer-Lecture.qmd" target="_blank">**Designing high-confidence embedded systems -- operating systems and real-time**</a> by <a href="https://faculty.cs.gwu.edu/gparmer/" target="_blank">Prof. Gabe Parmer</a>, CS Department, GWU. <a href="https://composite.seas.gwu.edu" target="_blank">Parmer Lab</a></li>      -->
          <!-- <li><a href="Spring2023_MidtermProjects.qmd" style="color:red;" target="_blank">Spring 2023 Midterm Project for Review</a></li> -->
          <!-- <li style="color:black"><a href="Week3.qmd" style="color:red;" target="_blank">Week-3 Notes</a></li> -->
        </ul>
      </td>
      <td>
        <ul>
          <li>In-class Raspberry Pi Lab (Ultrasound sensors)</li>
          <li>Proxmity sensing using Thonny IDE</li>
<!--           <li>Proxmity sensing using bash script</li>
 -->      <li style="color:black"><strong>Proxmity sensing on boot [Graded Lab Activity]</strong></li>
           <!-- <li><strong><a href="Downloads/LastName_ExecutiveSummary.docx" style="color:red;" target="_blank">HW2.1: Guest Lecture Summary [Download Template]</a></strong></li> <strong>HW2.1 Assigned: 02/09/2024; HW2.1 Due: 02/16/2024</strong> -->
           <!-- <li><strong><a href="Downloads/Midterm_Project_Proposal_CS4907.docx" style="color:red;" target="_blank">HW2.2: Midterm Project Proposal [Download Template]</a></strong></li> <strong>HW2.2 Assigned: 02/09/2024; HW2.2 Due: 02/18/2024</strong> -->
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<tr class="table-secondary">
      <th scope="row">Week 4 [02/12/2025]</th>
      <td>
        <ul>
          <!-- <li>IoT Architecture and Ecosystem</li>
          <li>Layers in IoT systems - 3 level  layer model</li>
          <li>Sensors</li>
          <li>Sensor types and considerations</li>
          <li>Understanding Analog and Digital Signals</li>
          <li>Fundamentals of signal visualization in time and frequency</li>       -->
          <li>Guest lecture: 
          <!-- **Anatomy of a real life IoT attack - Side Channel Attack (SCA) Analysis** by <a href="/Lectures_Speakers/Chowdary-bio-Feb162024.pdf"
          target="_blank">Chowdary  Yanamadala</a>, Technology Strategist <a href="https://arm.com" target="_blank">ARM</a> -->
          </li>        
          <!-- <li>Guest lecture: <a href="Week4-Yanamadala-ARM-Lecture.qmd" target="_blank">**Anatomy of a real life IoT attack - Side Channel Attack (SCA) Analysis**</a> by <a href="/Lectures_Speakers/Chowdary-bio-Feb162024.pdf" target="_blank">Chowdary  Yanamadala</a>, Technology Strategist <a href="https://arm.com" target="_blank">ARM</a></li>      -->
          <li> Discussion of Midterm Projects and setting course for updates and reporting</li>
          <!-- <li style="color:black"><a href="Week4.qmd" style="color:red;" target="_blank">Week-4 Notes</a></li> -->
        </ul>
      </td>
      <td>
        <ul>
          <li>dweet.io - it's like the Twitter of Things <a href="https://dweet.io"target="_blank"> dweet</a></li>
          <li>Fetching data from dweet</li>
          <li style="color:black"><strong>dweet an LED - Your first IoT program [Graded Lab Activity]</strong></li>
          <li style="color:black"><strong>Raspberry Pi messaging with Python scripts [Graded Lab Activity]</strong></li>
         <!-- <li><strong><a href="Downloads/LastName_ExecutiveSummary.docx" style="color:red;" target="_blank">HW3: Guest Lecture Summary [Download Template]</a></strong></li> <strong>HW3 Assigned: 02/16/2024; HW3 Due: 02/23/2024</strong> -->
        </ul>
      </td>
    </tr>
    
<tr class="table-secondary">
      <th scope="row">Week 5 [02/19/2025]</th>
      <td>
        <ul>
          <li>Guest lecture: 
          <!-- **Intersection of Industry 4.0 and Technology for Manufacturing in day-to-day applications** by <a href="/Lectures_Speakers/HadiImran-bio-Feb232024.pdf" target="_blank">Hadi Mohammed</a>, Digital Technologies Director of Factory 4.0 <a href="https://prattwhitney.com" target="_blank">Pratt and Whitney</a> -->
          </li> 
          <li>IoT Taxonomy - 5 layer model</li>         
          <!-- <li>Guest lecture: <a href="Week5-Mohammad-PrattWhitney-Lecture.qmd" target="_blank">**Intersection of Industry 4.0 and Technology for Manufacturing in day-to-day applications**</a> by <a href="/Lectures_Speakers/HadiImran-bio-Feb232024.pdf" target="_blank">Hadi Mohammed</a>, Digital Technologies Director of Factory 4.0 <a href="https://prattwhitney.com" target="_blank">Pratt and Whitney</a></li>  -->    
          <li>Service-oriented model of IoT</li>
          <li> Discussion of Midterm Projects and setting course for updates and reporting</li>
          <!-- <li style="color:black"><a href="Week5.qmd" style="color:red;" target="_blank">Week-5 Notes</a></li> -->

        </ul>
      </td>
      <td>
        <ul>
          <li style="color:black"><strong>In-class Flask API development [Graded Lab Activity]</strong></li>       
         <!-- <li><strong><a href="Downloads/LastName_ExecutiveSummary.docx" style="color:red;" target="_blank">HW4: Guest Lecture Summary [Download Template]</a></strong></li> <strong>HW4 Assigned: 02/23/2024; HW4 Due: 03/01/2024</strong> -->
        </ul>
      </td>
      <!--- <td>Column content</td> -->
    </tr>

<tr class="table-secondary">
      <th scope="row"> Week 7 [03/05/2025]</th>
      <td colspan="2" style="text-align: center">Midterm Project Presentations, Report and Live Demos due.
      <br><strong><a href="Downloads/LastName_HW_paper_review.docx" style="color:red;" target="_blank">Midterm project report template [Download Template]</a>
      </strong>
      <br><strong><a href="Downloads/AlZaabi_AlmayoofSpring2023_ProjectReport.pdf" style="color:red;" target="_blank">Sample project report</a>
      </strong></td>
      <!--- <td>Column content</td> -->
    </tr>
<!-- <tr class="table-secondary">
      <th scope="row"> [03/11/2025]</th>
      <td colspan="2" style="text-align: center">Midterm Project Report due.
      <!-- <br><strong><a href="Downloads/LastName_HW_paper_review.docx" style="color:red;" target="_blank">Midterm project report template [Download Template]</a></strong> -->
      <br><strong><a href="Downloads/AlZaabi_AlmayoofSpring2023_ProjectReport.pdf" style="color:red;" target="_blank">Sample project report</a>
      </strong></td>
      <!--- <td>Column content</td> -->
    </tr> -->
<tr class="table-secondary">
      <th scope="row"> [03/10/2025] to [03/15/2025]</th>
      <td colspan="2" style="text-align: center">Spring Break. 
      <br><strong>No class this week</strong></td> 
      <!--- <td>Column content</td> -->
    </tr>


  
<tr class="table-secondary">
      <th scope="row"> Week 13 [04/23/2025]</th>
      <td colspan="2" style="text-align: center">Final Project Presentations and Live Demos due.
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Final project presentation template [Download Template]</a>
      </strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>    

<tr class="table-secondary">
      <th scope="row"> [04/30/2025]</th>
      <td colspan="2" style="text-align: center"> Final Project Report due (Tentatively!).
      <!-- <br><strong><a href="Downloads/LastName_HW_paper_review.docx" style="color:red;" target="_blank">Final project report template [Download Template]</a>
      </strong> -->
      <br><strong><a href="Downloads/AlZaabi_AlmayoofSpring2023_ProjectReport.pdf" style="color:red;" target="_blank">Sample project report</a>
      </strong></td>
      <!--- <td>Column content</td> -->
    </tr>
    
<tr class="table-secondary">
      <th scope="row">[04/28/2025]</th>
      <td colspan="2" style="text-align: center"> Last Day of Classes 
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>    
<tr class="table-secondary">
      <th scope="row">[04/29/2025]</th>
      <td colspan="2" style="text-align: center"> Make-Up Day
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>   
<tr class="table-secondary">
      <th scope="row">[04/30/2025]</th>
      <td colspan="2" style="text-align: center"> Designated Monday
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>  
<tr class="table-secondary">
      <th scope="row">[05/01/2025] to [05/02/2025]</th>
      <td colspan="2" style="text-align: center"> Reading Days
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>     
<tr class="table-secondary">
      <th scope="row">[05/03/2025] to [05/09/2025]</th>
      <td colspan="2" style="text-align: center"> <strong>Final Examinations </strong>
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>        
<tr class="table-secondary">
      <th scope="row">[05/15/2025] to [05/18/2025]</th>
      <td colspan="2" style="text-align: center"> Commencement Weekend
      <!-- <br><strong><a href="Downloads/Midterm_presentation_template.pptx" style="color:red;" target="_blank">Midterm project presentation template [Download Template]</a></strong> -->
      </td> 
      <!--- <td>Column content</td> -->
    </tr>    
  </tbody>
</table>



<!-- <footer>
  <p>This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.<br>
  Author: Kartik Bulusu<br>
  Contact: <a href="mailto:bulusu@gwu.edu">bulusu</a><br>
  &copy; 2024 All rights reserved</p>
</footer> -->
